// Auto-generated by a11y-stories generate - DO NOT EDIT MANUALLY
// Source: axe-core rule "link-name"
// Generated: 2026-02-04T14:16:19.571Z

import type { Meta, StoryObj } from "@storybook/react";

/**
 * ## Rule: `link-name`
 *
 * Ensure links have discernible text
 *
 * - **WCAG:** 2.4.4, 4.1.2
 * - **Level:** A
 * - **Impact:** serious
 * - **Tags:** cat.name-role-value, wcag2a, wcag244, wcag412, section508
 * - **Reference:** [link-name](https://dequeuniversity.com/rules/axe/4.11/link-name?application=axeAPI)
 */
const meta: Meta = {
  title: "A11y Violations/links/link-name",
  parameters: {
    a11yReference: {
      ruleId: "link-name",
      expectedViolations: ["link-name"],
      wcag: ["2.4.4", "4.1.2"],
      impact: "serious",
      helpUrl: "https://dequeuniversity.com/rules/axe/4.11/link-name?application=axeAPI",
    },
    docs: {
      description: {
        component: "Ensure links have discernible text",
      },
    },
  },
};

export default meta;

type Story = StoryObj;

/**
 * ❌ VIOLATION: Link without text or accessible name
 */
export const Violation1: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<a href="/"></a>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: true,
      ruleId: "link-name",
      description: "Link without text or accessible name",
    },
  },
};

/**
 * ❌ VIOLATION: Link with image that has no alt
 */
export const Violation2: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<a href="/"><img src="logo.png"></a>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: true,
      ruleId: "link-name",
      description: "Link with image that has no alt",
    },
  },
};

/**
 * ✅ PASS: Link with text content
 */
export const Pass1: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<a href="/">Home</a>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: false,
      ruleId: "link-name",
      description: "Link with text content",
    },
  },
};

/**
 * ✅ PASS: Link with aria-label and decorative image
 */
export const Pass2: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<a href="/" aria-label="Go to home page"><img src="home.png" alt=""></a>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: false,
      ruleId: "link-name",
      description: "Link with aria-label and decorative image",
    },
  },
};
