// Auto-generated by a11y-stories generate - DO NOT EDIT MANUALLY
// Source: axe-core rule "label"
// Generated: 2026-02-04T14:16:19.570Z

import type { Meta, StoryObj } from "@storybook/react";

/**
 * ## Rule: `label`
 *
 * Ensure every form element has a label
 *
 * - **WCAG:** 4.1.2
 * - **Level:** A
 * - **Impact:** critical
 * - **Tags:** cat.forms, wcag2a, wcag412, section508, section508.22.n
 * - **Reference:** [label](https://dequeuniversity.com/rules/axe/4.11/label?application=axeAPI)
 */
const meta: Meta = {
  title: "A11y Violations/forms/label",
  parameters: {
    a11yReference: {
      ruleId: "label",
      expectedViolations: ["label"],
      wcag: ["4.1.2"],
      impact: "critical",
      helpUrl: "https://dequeuniversity.com/rules/axe/4.11/label?application=axeAPI",
    },
    docs: {
      description: {
        component: "Ensure every form element has a label",
      },
    },
  },
};

export default meta;

type Story = StoryObj;

/**
 * ❌ VIOLATION: Input without label
 */
export const Violation1: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<input type="text" placeholder="Enter name">`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: true,
      ruleId: "label",
      description: "Input without label",
    },
  },
};

/**
 * ❌ VIOLATION: Email input without label
 */
export const Violation2: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<input type="email">`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: true,
      ruleId: "label",
      description: "Email input without label",
    },
  },
};

/**
 * ✅ PASS: Input with associated label
 */
export const Pass1: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<label for="name">Name</label><input id="name" type="text">`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: false,
      ruleId: "label",
      description: "Input with associated label",
    },
  },
};

/**
 * ✅ PASS: Input wrapped in label
 */
export const Pass2: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<label>Name <input type="text"></label>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: false,
      ruleId: "label",
      description: "Input wrapped in label",
    },
  },
};

/**
 * ✅ PASS: Input with aria-label
 */
export const Pass3: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<input type="text" aria-label="Enter your name">`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: false,
      ruleId: "label",
      description: "Input with aria-label",
    },
  },
};
