// Auto-generated by a11y-stories generate - DO NOT EDIT MANUALLY
// Source: axe-core rule "select-name"
// Generated: 2026-02-04T14:16:19.575Z

import type { Meta, StoryObj } from "@storybook/react";

/**
 * ## Rule: `select-name`
 *
 * Ensure select element has an accessible name
 *
 * - **WCAG:** 4.1.2
 * - **Level:** A
 * - **Impact:** critical
 * - **Tags:** cat.forms, wcag2a, wcag412, section508, section508.22.n
 * - **Reference:** [select-name](https://dequeuniversity.com/rules/axe/4.11/select-name?application=axeAPI)
 */
const meta: Meta = {
  title: "A11y Violations/forms/select-name",
  parameters: {
    a11yReference: {
      ruleId: "select-name",
      expectedViolations: ["select-name"],
      wcag: ["4.1.2"],
      impact: "critical",
      helpUrl: "https://dequeuniversity.com/rules/axe/4.11/select-name?application=axeAPI",
    },
    docs: {
      description: {
        component: "Ensure select element has an accessible name",
      },
    },
  },
};

export default meta;

type Story = StoryObj;

/**
 * ❌ VIOLATION: Select without label
 */
export const Violation: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<select><option>Option 1</option></select>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: true,
      ruleId: "select-name",
      description: "Select without label",
    },
  },
};

/**
 * ✅ PASS: Select with associated label
 */
export const Pass: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<label for="choice">Choose:</label><select id="choice"><option>Option 1</option></select>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: false,
      ruleId: "select-name",
      description: "Select with associated label",
    },
  },
};
