// Auto-generated index of all a11y reference stories
// Generated: 2026-02-04T14:16:19.576Z

// This file is for reference only - Storybook auto-discovers stories
// based on the stories glob pattern in .storybook/main.ts

export const GENERATED_STORY_COUNT = 67;

export const GENERATED_RULES = [
  "area-alt",
  "aria-allowed-attr",
  "aria-braille-equivalent",
  "aria-command-name",
  "aria-conditional-attr",
  "aria-deprecated-role",
  "aria-hidden-body",
  "aria-hidden-focus",
  "aria-input-field-name",
  "aria-meter-name",
  "aria-progressbar-name",
  "aria-prohibited-attr",
  "aria-required-attr",
  "aria-required-children",
  "aria-required-parent",
  "aria-roledescription",
  "aria-roles",
  "aria-toggle-field-name",
  "aria-tooltip-name",
  "aria-valid-attr-value",
  "aria-valid-attr",
  "audio-caption",
  "autocomplete-valid",
  "avoid-inline-spacing",
  "blink",
  "button-name",
  "bypass",
  "color-contrast",
  "css-orientation-lock",
  "definition-list",
  "dlitem",
  "document-title",
  "duplicate-id-aria",
  "form-field-multiple-labels",
  "frame-focusable-content",
  "frame-title-unique",
  "frame-title",
  "html-has-lang",
  "html-lang-valid",
  "html-xml-lang-mismatch",
  "image-alt",
  "input-button-name",
  "input-image-alt",
  "label",
  "link-in-text-block",
  "link-name",
  "list",
  "listitem",
  "marquee",
  "meta-refresh",
  "meta-viewport",
  "nested-interactive",
  "no-autoplay-audio",
  "object-alt",
  "p-as-heading",
  "role-img-alt",
  "scrollable-region-focusable",
  "select-name",
  "server-side-image-map",
  "summary-name",
  "svg-img-alt",
  "table-fake-caption",
  "td-has-header",
  "td-headers-attr",
  "th-has-data-cells",
  "valid-lang",
  "video-caption",
];

export const STORIES_BY_CATEGORY = {
  other: [
    "area-alt",
    "aria-braille-equivalent",
    "aria-conditional-attr",
    "aria-deprecated-role",
    "aria-hidden-body",
    "aria-meter-name",
    "aria-progressbar-name",
    "aria-prohibited-attr",
    "aria-roledescription",
    "aria-roles",
    "aria-tooltip-name",
    "avoid-inline-spacing",
    "blink",
    "css-orientation-lock",
    "form-field-multiple-labels",
    "frame-focusable-content",
    "html-xml-lang-mismatch",
    "marquee",
    "meta-refresh",
    "meta-viewport",
    "scrollable-region-focusable",
    "server-side-image-map",
    "summary-name",
    "table-fake-caption",
    "td-has-header",
    "valid-lang",
  ],
  aria: [
    "aria-allowed-attr",
    "aria-command-name",
    "aria-hidden-focus",
    "aria-input-field-name",
    "aria-required-attr",
    "aria-required-children",
    "aria-required-parent",
    "aria-toggle-field-name",
    "aria-valid-attr-value",
    "aria-valid-attr",
  ],
  media: ["audio-caption", "no-autoplay-audio", "video-caption"],
  forms: ["autocomplete-valid", "label", "select-name"],
  buttons: ["button-name", "input-button-name"],
  document: ["bypass", "document-title", "html-has-lang", "html-lang-valid"],
  color: ["color-contrast"],
  lists: ["definition-list", "dlitem", "list", "listitem"],
  structure: ["duplicate-id-aria", "nested-interactive"],
  frames: ["frame-title-unique", "frame-title"],
  images: ["image-alt", "input-image-alt", "object-alt", "role-img-alt", "svg-img-alt"],
  links: ["link-in-text-block", "link-name"],
  headings: ["p-as-heading"],
  tables: ["td-headers-attr", "th-has-data-cells"],
};
