/**
 * Workspace Repo Commands
 *
 * CLI commands for managing a dedicated workspace repository.
 * The workspace repo contains versioned configuration for a multi-repo workspace:
 * - CLAUDE.md (auto-generated + manual sections)
 * - workspace.yaml (workspace definition)
 * - .agent-os/ (agent configuration)
 * - scripts/install.sh (setup script)
 */

import * as path from "node:path";
import type { Command } from "commander";
import { repoInitCommand } from "./repo-init.js";
import { repoInstallCommand } from "./repo-install.js";
import { repoStatusCommand } from "./repo-status.js";
import { repoSyncCommand } from "./repo-sync.js";

// Re-export types
export type { RepoInitOptions, RepoInitResult } from "./repo-init.js";
export type { RepoSyncOptions, RepoSyncResult } from "./repo-sync.js";
export type { RepoInstallOptions, RepoInstallResult, SymlinkInfo } from "./repo-install.js";
export type {
  RepoStatusOptions,
  RepoStatusResult,
  SymlinkStatus,
  GitStatus,
  ClaudeMdStatus,
  WorkspaceYamlSummary,
} from "./repo-status.js";

// Re-export command functions
export { repoInitCommand } from "./repo-init.js";
export { repoSyncCommand } from "./repo-sync.js";
export { repoInstallCommand } from "./repo-install.js";
export { repoStatusCommand } from "./repo-status.js";

// Re-export utility types
export type {
  ParsedAgentsMd,
  ExtractedStack,
  ExtractedCommands,
} from "./utils/agents-parser.js";
export type {
  WorkspaceDefinition,
  WorkspaceRepoDefinition,
  GenerateOptions,
  GenerateResult,
} from "./utils/claude-generator.js";

// Re-export utility functions
export {
  parseAgentsMd,
  parseAllAgentsMd,
  findAgentsMdPath,
  summarizeAgentsMd,
} from "./utils/agents-parser.js";
export {
  generateClaudeMd,
  hasAutoGeneratedMarkers,
  getAutoGeneratedSections,
  MARKERS,
} from "./utils/claude-generator.js";

/**
 * Register the workspace repo command group
 *
 * This should be called from workspace-status.ts to add the "repo" subcommand
 * under the "workspace" command.
 *
 * Commands:
 * - workspace repo init - Create a new workspace repo
 * - workspace repo sync - Sync CLAUDE.md from repos
 * - workspace repo install - Install symlinks
 * - workspace repo status - Show workspace repo status
 */
export function registerWorkspaceRepoCommands(workspace: Command): void {
  const repo = workspace
    .command("repo")
    .description("Manage workspace repository for versioned configuration");

  // repo init
  repo
    .command("init")
    .description("Create a new workspace repository with CLAUDE.md and configuration")
    .option("-w, --workspace <path>", "Workspace path", process.cwd())
    .option("-n, --name <name>", "Workspace name (repo will be <name>-workspace)", "workspace")
    .option("-p, --path <path>", "Custom path for workspace repo")
    .option("--symlinks", "Create symlinks after init")
    .option("--force", "Force overwrite existing repo")
    .option("--json", "Output as JSON")
    .action(async (options) => {
      const result = await repoInitCommand({
        workspacePath: path.resolve(options.workspace),
        name: options.name,
        repoPath: options.path ? path.resolve(options.path) : undefined,
        createSymlinks: options.symlinks,
        force: options.force,
        json: options.json,
      });

      if (options.json) {
        console.log(JSON.stringify(result, null, 2));
      } else if (result.success) {
        console.log(result.formatted);
      } else {
        console.error(`✗ ${result.error}`);
        process.exit(1);
      }
    });

  // repo sync
  repo
    .command("sync")
    .description("Sync CLAUDE.md from repository AGENTS.md files")
    .option("-w, --workspace <path>", "Workspace path", process.cwd())
    .option("-p, --repo-path <path>", "Path to workspace repo (auto-detected)")
    .option("--dry-run", "Preview changes without writing")
    .option("--json", "Output as JSON")
    .action(async (options) => {
      const result = await repoSyncCommand({
        workspacePath: path.resolve(options.workspace),
        repoPath: options.repoPath ? path.resolve(options.repoPath) : undefined,
        dryRun: options.dryRun,
        json: options.json,
      });

      if (options.json) {
        console.log(JSON.stringify(result, null, 2));
      } else if (result.success) {
        console.log(result.formatted);
      } else {
        console.error(`✗ ${result.error}`);
        process.exit(1);
      }
    });

  // repo install
  repo
    .command("install")
    .description("Install symlinks from workspace repo to workspace root")
    .option("-w, --workspace <path>", "Workspace path", process.cwd())
    .option("-p, --repo-path <path>", "Path to workspace repo (auto-detected)")
    .option("--force", "Force overwrite existing files (backup first)")
    .option("--json", "Output as JSON")
    .action(async (options) => {
      const result = await repoInstallCommand({
        workspacePath: path.resolve(options.workspace),
        repoPath: options.repoPath ? path.resolve(options.repoPath) : undefined,
        force: options.force,
        json: options.json,
      });

      if (options.json) {
        console.log(JSON.stringify(result, null, 2));
      } else if (result.success) {
        console.log(result.formatted);
      } else {
        console.error(`✗ ${result.error}`);
        process.exit(1);
      }
    });

  // repo status
  repo
    .command("status")
    .description("Show workspace repository status")
    .option("-w, --workspace <path>", "Workspace path", process.cwd())
    .option("-p, --repo-path <path>", "Path to workspace repo (auto-detected)")
    .option("--json", "Output as JSON")
    .action(async (options) => {
      const result = await repoStatusCommand({
        workspacePath: path.resolve(options.workspace),
        repoPath: options.repoPath ? path.resolve(options.repoPath) : undefined,
        json: options.json,
      });

      if (options.json) {
        console.log(JSON.stringify(result, null, 2));
      } else if (result.success) {
        console.log(result.formatted);
      } else {
        console.error(`✗ ${result.error}`);
        process.exit(1);
      }
    });
}
