// Auto-generated by a11y-stories generate - DO NOT EDIT MANUALLY
// Source: axe-core rule "color-contrast"
// Generated: 2026-02-04T14:16:19.569Z

import type { Meta, StoryObj } from "@storybook/react";

/**
 * ## Rule: `color-contrast`
 *
 * Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds
 *
 * - **WCAG:** 1.4.3
 * - **Level:** AA
 * - **Impact:** serious
 * - **Tags:** cat.color, wcag2aa, wcag143, TTv5, TT13.c
 * - **Reference:** [color-contrast](https://dequeuniversity.com/rules/axe/4.11/color-contrast?application=axeAPI)
 */
const meta: Meta = {
  title: "A11y Violations/color/color-contrast",
  parameters: {
    a11yReference: {
      ruleId: "color-contrast",
      expectedViolations: ["color-contrast"],
      wcag: ["1.4.3"],
      impact: "serious",
      helpUrl: "https://dequeuniversity.com/rules/axe/4.11/color-contrast?application=axeAPI",
    },
    docs: {
      description: {
        component:
          "Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds",
      },
    },
  },
};

export default meta;

type Story = StoryObj;

/**
 * ❌ VIOLATION: Text with insufficient color contrast
 */
export const Violation: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<p style="color: #aaa; background-color: #fff;">Low contrast text</p>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: true,
      ruleId: "color-contrast",
      description: "Text with insufficient color contrast",
    },
  },
};

/**
 * ✅ PASS: Text with sufficient color contrast
 */
export const Pass: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<p style="color: #333; background-color: #fff;">High contrast text</p>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: false,
      ruleId: "color-contrast",
      description: "Text with sufficient color contrast",
    },
  },
};
