// Auto-generated by a11y-stories generate - DO NOT EDIT MANUALLY
// Source: axe-core rule "button-name"
// Generated: 2026-02-04T14:16:19.568Z

import type { Meta, StoryObj } from "@storybook/react";

/**
 * ## Rule: `button-name`
 *
 * Ensure buttons have discernible text
 *
 * - **WCAG:** 4.1.2
 * - **Level:** A
 * - **Impact:** critical
 * - **Tags:** cat.name-role-value, wcag2a, wcag412, section508, section508.22.a
 * - **Reference:** [button-name](https://dequeuniversity.com/rules/axe/4.11/button-name?application=axeAPI)
 */
const meta: Meta = {
  title: "A11y Violations/buttons/button-name",
  parameters: {
    a11yReference: {
      ruleId: "button-name",
      expectedViolations: ["button-name"],
      wcag: ["4.1.2"],
      impact: "critical",
      helpUrl: "https://dequeuniversity.com/rules/axe/4.11/button-name?application=axeAPI",
    },
    docs: {
      description: {
        component: "Ensure buttons have discernible text",
      },
    },
  },
};

export default meta;

type Story = StoryObj;

/**
 * ❌ VIOLATION: Button without text or accessible name
 */
export const Violation1: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<button></button>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: true,
      ruleId: "button-name",
      description: "Button without text or accessible name",
    },
  },
};

/**
 * ❌ VIOLATION: Button with only hidden content
 */
export const Violation2: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<button><span aria-hidden="true">×</span></button>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: true,
      ruleId: "button-name",
      description: "Button with only hidden content",
    },
  },
};

/**
 * ✅ PASS: Button with text content
 */
export const Pass1: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<button>Submit</button>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: false,
      ruleId: "button-name",
      description: "Button with text content",
    },
  },
};

/**
 * ✅ PASS: Icon button with aria-label
 */
export const Pass2: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<button aria-label="Close"><span aria-hidden="true">×</span></button>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: false,
      ruleId: "button-name",
      description: "Icon button with aria-label",
    },
  },
};
