// Auto-generated by a11y-stories generate - DO NOT EDIT MANUALLY
// Source: axe-core rule "aria-hidden-focus"
// Generated: 2026-02-04T14:16:19.566Z

import type { Meta, StoryObj } from "@storybook/react";

/**
 * ## Rule: `aria-hidden-focus`
 *
 * Ensure aria-hidden elements are not focusable nor contain focusable elements
 *
 * - **WCAG:** 4.1.2
 * - **Level:** A
 * - **Impact:** serious
 * - **Tags:** cat.name-role-value, wcag2a, wcag412, TTv5, TT6.a
 * - **Reference:** [aria-hidden-focus](https://dequeuniversity.com/rules/axe/4.11/aria-hidden-focus?application=axeAPI)
 */
const meta: Meta = {
  title: "A11y Violations/aria/aria-hidden-focus",
  parameters: {
    a11yReference: {
      ruleId: "aria-hidden-focus",
      expectedViolations: ["aria-hidden-focus"],
      wcag: ["4.1.2"],
      impact: "serious",
      helpUrl: "https://dequeuniversity.com/rules/axe/4.11/aria-hidden-focus?application=axeAPI",
    },
    docs: {
      description: {
        component: "Ensure aria-hidden elements are not focusable nor contain focusable elements",
      },
    },
  },
};

export default meta;

type Story = StoryObj;

/**
 * ❌ VIOLATION: Focusable element inside aria-hidden container
 */
export const Violation1: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<div aria-hidden="true"><button>Focusable but hidden</button></div>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: true,
      ruleId: "aria-hidden-focus",
      description: "Focusable element inside aria-hidden container",
    },
  },
};

/**
 * ❌ VIOLATION: Button with aria-hidden
 */
export const Violation2: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<button aria-hidden="true">Hidden button</button>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: true,
      ruleId: "aria-hidden-focus",
      description: "Button with aria-hidden",
    },
  },
};

/**
 * ✅ PASS: Non-focusable content in aria-hidden
 */
export const Pass: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<div aria-hidden="true"><span>Decorative text</span></div>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: false,
      ruleId: "aria-hidden-focus",
      description: "Non-focusable content in aria-hidden",
    },
  },
};
