/**
 * Claude CLI integration
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";
import { execa } from "execa";
import type { GitHubIssue } from "./types.js";

/**
 * Get the path to the issue context file
 */
function getContextFilePath(): string {
  const homeDir = process.env.HOME || process.env.USERPROFILE || "";
  return path.join(homeDir, ".devac", "issue-context.md");
}

/**
 * Write issue context to a file that Claude can read
 */
export async function writeIssueContext(issue: GitHubIssue, worktreePath: string): Promise<string> {
  const contextPath = getContextFilePath();
  const dir = path.dirname(contextPath);

  await fs.mkdir(dir, { recursive: true });

  const content = `# Issue #${issue.number}: ${issue.title}

## Worktree Location
\`${worktreePath}\`

## Issue Body

${issue.body}

---
*This context file was generated by devac-worktree. Claude can use this to understand the issue.*
`;

  await fs.writeFile(contextPath, content);
  return contextPath;
}

/**
 * Launch Claude CLI in a directory
 */
export async function launchClaude(
  directory: string,
  options?: { resume?: string; print?: string }
): Promise<void> {
  const args: string[] = [];

  if (options?.resume) {
    args.push("--resume", options.resume);
  }

  if (options?.print) {
    args.push("--print", options.print);
  }

  // Launch Claude CLI in the worktree directory
  // Use spawn with inherit to attach to terminal
  await execa("claude", args, {
    cwd: directory,
    stdio: "inherit",
    env: {
      ...process.env,
      // Ensure Claude sees the worktree as the working directory
      PWD: directory,
    },
  });
}

/**
 * Check if Claude CLI is installed
 */
export async function isClaudeInstalled(): Promise<boolean> {
  try {
    await execa("claude", ["--version"]);
    return true;
  } catch {
    return false;
  }
}

/**
 * Generate initial prompt for Claude based on issue
 */
export function generateInitialPrompt(issue: GitHubIssue): string {
  return `I'm starting work on issue #${issue.number}: "${issue.title}"

Please read the issue context at ~/.devac/issue-context.md and help me implement this.

The issue details:
${issue.body.slice(0, 500)}${issue.body.length > 500 ? "..." : ""}

Let's start by understanding what needs to be done and creating an implementation plan.`;
}
