// Auto-generated by a11y-stories generate - DO NOT EDIT MANUALLY
// Source: axe-core rule "list"
// Generated: 2026-02-04T14:16:19.572Z

import type { Meta, StoryObj } from "@storybook/react";

/**
 * ## Rule: `list`
 *
 * Ensure that lists are structured correctly
 *
 * - **WCAG:** 1.3.1
 * - **Level:** A
 * - **Impact:** moderate
 * - **Tags:** cat.structure, wcag2a, wcag131, EN-301-549, EN-9.1.3.1
 * - **Reference:** [list](https://dequeuniversity.com/rules/axe/4.11/list?application=axeAPI)
 */
const meta: Meta = {
  title: "A11y Violations/lists/list",
  parameters: {
    a11yReference: {
      ruleId: "list",
      expectedViolations: ["list"],
      wcag: ["1.3.1"],
      impact: "moderate",
      helpUrl: "https://dequeuniversity.com/rules/axe/4.11/list?application=axeAPI",
    },
    docs: {
      description: {
        component: "Ensure that lists are structured correctly",
      },
    },
  },
};

export default meta;

type Story = StoryObj;

/**
 * ❌ VIOLATION: List with non-li child
 */
export const Violation: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<ul><div>Not a list item</div></ul>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: true,
      ruleId: "list",
      description: "List with non-li child",
    },
  },
};

/**
 * ✅ PASS: Proper list structure
 */
export const Pass: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<ul><li>List item 1</li><li>List item 2</li></ul>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: false,
      ruleId: "list",
      description: "Proper list structure",
    },
  },
};
