// Auto-generated by a11y-stories generate - DO NOT EDIT MANUALLY
// Source: axe-core rule "listitem"
// Generated: 2026-02-04T14:16:19.575Z

import type { Meta, StoryObj } from "@storybook/react";

/**
 * ## Rule: `listitem`
 *
 * Ensure <li> elements are used semantically
 *
 * - **WCAG:** 1.3.1
 * - **Level:** A
 * - **Impact:** moderate
 * - **Tags:** cat.structure, wcag2a, wcag131, EN-301-549, EN-9.1.3.1
 * - **Reference:** [listitem](https://dequeuniversity.com/rules/axe/4.11/listitem?application=axeAPI)
 */
const meta: Meta = {
  title: "A11y Violations/lists/listitem",
  parameters: {
    a11yReference: {
      ruleId: "listitem",
      expectedViolations: ["listitem"],
      wcag: ["1.3.1"],
      impact: "moderate",
      helpUrl: "https://dequeuniversity.com/rules/axe/4.11/listitem?application=axeAPI",
    },
    docs: {
      description: {
        component: "Ensure <li> elements are used semantically",
      },
    },
  },
};

export default meta;

type Story = StoryObj;

/**
 * ❌ VIOLATION: List item outside of list
 */
export const Violation: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<li>Orphan list item</li>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: true,
      ruleId: "listitem",
      description: "List item outside of list",
    },
  },
};

/**
 * ✅ PASS: List item inside list
 */
export const Pass: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<ul><li>Proper list item</li></ul>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: false,
      ruleId: "listitem",
      description: "List item inside list",
    },
  },
};
