#!/usr/bin/env node
/**
 * Generate version.ts files for packages
 *
 * Reads version from package.json and writes a version.ts file
 * that exports the VERSION constant.
 *
 * Usage: node scripts/generate-version.mjs packages/devac-core
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const packageDir = process.argv[2];

if (!packageDir) {
  console.error("Usage: node scripts/generate-version.mjs <package-dir>");
  process.exit(1);
}

const packageJsonPath = join(packageDir, "package.json");
const versionTsPath = join(packageDir, "src", "version.ts");

try {
  const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf-8"));
  const version = packageJson.version;

  const content = `// Auto-generated by scripts/generate-version.mjs - DO NOT EDIT
export const VERSION = "${version}";
`;

  writeFileSync(versionTsPath, content);
  console.log(`Generated ${versionTsPath} with VERSION = "${version}"`);
} catch (error) {
  console.error(`Failed to generate version.ts: ${error.message}`);
  process.exit(1);
}
