// Auto-generated by a11y-stories generate - DO NOT EDIT MANUALLY
// Source: axe-core rule "image-alt"
// Generated: 2026-02-04T14:16:19.569Z

import type { Meta, StoryObj } from "@storybook/react";

/**
 * ## Rule: `image-alt`
 *
 * Ensure <img> elements have alternative text or a role of none or presentation
 *
 * - **WCAG:** 1.1.1
 * - **Level:** A
 * - **Impact:** critical
 * - **Tags:** cat.text-alternatives, wcag2a, wcag111, section508, section508.22.a
 * - **Reference:** [image-alt](https://dequeuniversity.com/rules/axe/4.11/image-alt?application=axeAPI)
 */
const meta: Meta = {
  title: "A11y Violations/images/image-alt",
  parameters: {
    a11yReference: {
      ruleId: "image-alt",
      expectedViolations: ["image-alt"],
      wcag: ["1.1.1"],
      impact: "critical",
      helpUrl: "https://dequeuniversity.com/rules/axe/4.11/image-alt?application=axeAPI",
    },
    docs: {
      description: {
        component: "Ensure <img> elements have alternative text or a role of none or presentation",
      },
    },
  },
};

export default meta;

type Story = StoryObj;

/**
 * ❌ VIOLATION: Image without alt attribute
 */
export const Violation1: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<img src="test.png">`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: true,
      ruleId: "image-alt",
      description: "Image without alt attribute",
    },
  },
};

/**
 * ❌ VIOLATION: Image with empty alt (when not decorative)
 */
export const Violation2: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<img src="test.png" alt="">`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: true,
      ruleId: "image-alt",
      description: "Image with empty alt (when not decorative)",
    },
  },
};

/**
 * ✅ PASS: Image with descriptive alt text
 */
export const Pass1: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<img src="test.png" alt="A test image">`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: false,
      ruleId: "image-alt",
      description: "Image with descriptive alt text",
    },
  },
};

/**
 * ✅ PASS: Decorative image with role=presentation
 */
export const Pass2: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<img src="test.png" alt="" role="presentation">`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: false,
      ruleId: "image-alt",
      description: "Decorative image with role=presentation",
    },
  },
};
