// Auto-generated by a11y-stories generate - DO NOT EDIT MANUALLY
// Source: axe-core rule "role-img-alt"
// Generated: 2026-02-04T14:16:19.575Z

import type { Meta, StoryObj } from "@storybook/react";

/**
 * ## Rule: `role-img-alt`
 *
 * Ensure [role="img"] elements have alternative text
 *
 * - **WCAG:** 1.1.1
 * - **Level:** A
 * - **Impact:** moderate
 * - **Tags:** cat.text-alternatives, wcag2a, wcag111, section508, section508.22.a
 * - **Reference:** [role-img-alt](https://dequeuniversity.com/rules/axe/4.11/role-img-alt?application=axeAPI)
 */
const meta: Meta = {
  title: "A11y Violations/images/role-img-alt",
  parameters: {
    a11yReference: {
      ruleId: "role-img-alt",
      expectedViolations: ["role-img-alt"],
      wcag: ["1.1.1"],
      impact: "moderate",
      helpUrl: "https://dequeuniversity.com/rules/axe/4.11/role-img-alt?application=axeAPI",
    },
    docs: {
      description: {
        component: 'Ensure [role="img"] elements have alternative text',
      },
    },
  },
};

export default meta;

type Story = StoryObj;

/**
 * ❌ VIOLATION: Element with role=img but no accessible name
 */
export const Violation: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<span role="img">🎉</span>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: true,
      ruleId: "role-img-alt",
      description: "Element with role=img but no accessible name",
    },
  },
};

/**
 * ✅ PASS: Element with role=img and aria-label
 */
export const Pass: Story = {
  render: () => (
    <div
      dangerouslySetInnerHTML={{
        __html: `<span role="img" aria-label="Celebration emoji">🎉</span>`,
      }}
    />
  ),
  parameters: {
    a11yReference: {
      shouldViolate: false,
      ruleId: "role-img-alt",
      description: "Element with role=img and aria-label",
    },
  },
};
